# Generated by Django 5.2.9 on 2025-12-28 05:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('people', '0006_remove_personorganization_people_pers_org_id_b113d9_idx_and_more'),
        ('tickets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtemplate',
            name='ticket_templates',
            field=models.ManyToManyField(blank=True, related_name='event_templates', to='tickets.tickettemplate'),
        ),
        migrations.AddField(
            model_name='event',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='events', to='events.eventtemplate'),
        ),
        migrations.AddField(
            model_name='shift',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='events.event'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='assigned_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shift_assignments', to='people.person'),
        ),
        migrations.AddField(
            model_name='shiftassignment',
            name='shift',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='events.shift'),
        ),
        migrations.AlterUniqueTogether(
            name='eventtemplate',
            unique_together={('org', 'name')},
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_status', 'modified_at'], name='events_even_event_s_f6678e_idx'),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['event', 'is_default'], name='events_shif_event_i_16472d_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['shift'], name='events_shif_shift_i_4213e9_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['person'], name='events_shif_person__dd28e2_idx'),
        ),
        migrations.AddIndex(
            model_name='shiftassignment',
            index=models.Index(fields=['status'], name='events_shif_status_5af16f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='shiftassignment',
            unique_together={('shift', 'person')},
        ),
    ]
