# Generated by Django 5.2.9 on 2025-12-27 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventtemplate',
            name='ticket_templates',
            field=models.ManyToManyField(blank=True, related_name='event_templates', to='tickets.tickettemplate'),
        ),
    ]
