# Generated by Django 5.2.9 on 2025-12-23 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_alter_event_description_alter_event_location_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift',
            name='capacity',
            field=models.PositiveIntegerField(default=0, help_text='Set to 0 for unlimited capacity'),
        ),
    ]
