# Generated by Django 5.2.9 on 2025-12-25 05:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_shiftassignment_delete_shiftsignup_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('finished', 'Finished')], default='draft', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='owned_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events_owned', to=settings.AUTH_USER_MODEL),
        ),
    ]
