# Generated by Django 5.2.9 on 2025-12-25 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_event_event_status_event_owned_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='shift',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='shift',
            name='is_hidden',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='shift',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name='shift',
            index=models.Index(fields=['event', 'is_default'], name='events_shif_event_i_16472d_idx'),
        ),
    ]
