# Generated by Django 5.2.9 on 2025-12-27 05:36

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_shift_is_default_shift_is_hidden_and_more'),
        ('orgs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('finished', 'Finished'), ('canceled', 'Canceled')], default='draft', max_length=20),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['event_status', 'modified_at'], name='events_even_event_s_f6678e_idx'),
        ),
    ]
