# Generated by Django 5.2.9 on 2025-12-23 19:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('orgs', '0001_initial'),
        ('people', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('note', 'Note'), ('call', 'Call'), ('text', 'Text'), ('knock', 'Door Knock'), ('email', 'Email'), ('event_checkin', 'Event Check-in'), ('custom', 'Custom')], max_length=30)),
                ('related_object_id', models.UUIDField(blank=True, null=True)),
                ('occurred_at', models.DateTimeField()),
                ('summary', models.CharField(blank=True, max_length=200, null=True)),
                ('details', models.TextField(blank=True, null=True)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='orgs.organization')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='people.person')),
                ('related_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype')),
            ],
            options={
                'indexes': [models.Index(fields=['org', 'occurred_at'], name='activities__org_id_7d72db_idx'), models.Index(fields=['org', 'kind'], name='activities__org_id_6f58b7_idx'), models.Index(fields=['org', 'person', 'occurred_at'], name='activities__org_id_04074f_idx')],
            },
        ),
    ]
