# Generated by Django 5.2.9 on 2025-12-23 21:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='details',
            field=models.TextField(blank=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='summary',
            field=models.CharField(blank=True, default='', max_length=200),
            preserve_default=False,
        ),
    ]
