# Generated by Django 5.2.9 on 2025-12-23 19:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('orgs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('phone', models.CharField(blank=True, max_length=50, null=True)),
                ('address_line1', models.CharField(blank=True, max_length=200, null=True)),
                ('address_line2', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=100, null=True)),
                ('state', models.CharField(blank=True, max_length=50, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=20, null=True)),
                ('attributes', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'indexes': [models.Index(fields=['full_name'], name='people_pers_full_na_9fcb6b_idx'), models.Index(fields=['email'], name='people_pers_email_52ffb2_idx'), models.Index(fields=['phone'], name='people_pers_phone_b55729_idx')],
            },
        ),
        migrations.CreateModel(
            name='PersonTag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_tags', to='orgs.organization')),
            ],
        ),
        migrations.CreateModel(
            name='PersonTagging',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggings', to='people.person')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taggings', to='people.persontag')),
            ],
        ),
        migrations.CreateModel(
            name='PersonOrganization',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('member', 'Member'), ('volunteer', 'Volunteer'), ('lead', 'Lead'), ('staff', 'Staff')], default='volunteer', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='people_links', to='orgs.organization')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='org_links', to='people.person')),
            ],
            options={
                'indexes': [models.Index(fields=['org', 'role'], name='people_pers_org_id_b113d9_idx'), models.Index(fields=['person', 'org'], name='people_pers_person__5f0687_idx')],
                'unique_together': {('person', 'org')},
            },
        ),
        migrations.AddIndex(
            model_name='persontag',
            index=models.Index(fields=['org', 'name'], name='people_pers_org_id_94a8e7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='persontag',
            unique_together={('org', 'name')},
        ),
        migrations.AddIndex(
            model_name='persontagging',
            index=models.Index(fields=['person'], name='people_pers_person__10bf22_idx'),
        ),
        migrations.AddIndex(
            model_name='persontagging',
            index=models.Index(fields=['tag'], name='people_pers_tag_id_1b7781_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='persontagging',
            unique_together={('person', 'tag')},
        ),
    ]
