# Generated by Django 5.2.9 on 2025-12-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='personorganization',
            options={'verbose_name': 'Org Membership', 'verbose_name_plural': 'Org Memberships'},
        ),
        migrations.RemoveIndex(
            model_name='persontag',
            name='people_pers_org_id_94a8e7_idx',
        ),
        migrations.AddField(
            model_name='persontag',
            name='color',
            field=models.CharField(choices=[('red', 'Red'), ('orange', 'Orange'), ('yellow', 'Yellow'), ('green', 'Green'), ('blue', 'Blue'), ('purple', 'Purple'), ('grey', 'Grey')], default='grey', max_length=16),
        ),
    ]
