# Generated by Django 5.2.9 on 2025-12-23 19:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
        ('people', '0002_alter_personorganization_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persontag',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='person_tags', to='orgs.organization'),
        ),
    ]
