# Generated by Django 5.2.9 on 2025-12-23 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('people', '0004_alter_person_address_line1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='discord',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
