# Generated by Django 5.2.9 on 2025-12-24 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
        ('people', '0005_person_discord'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='personorganization',
            name='people_pers_org_id_b113d9_idx',
        ),
        migrations.RemoveField(
            model_name='personorganization',
            name='role',
        ),
        migrations.AddIndex(
            model_name='personorganization',
            index=models.Index(fields=['org'], name='people_pers_org_id_1691ce_idx'),
        ),
    ]
