# Generated by Django 5.2.9 on 2025-12-28 05:45

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        ('orgs', '0001_initial'),
        ('people', '0006_remove_personorganization_people_pers_org_id_b113d9_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketActionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(help_text='Slug to uniquely identify this action template', unique=True)),
                ('action_type', models.CharField(choices=[('noop', 'No-op (status changes only)'), ('update_shift_status', 'Update shift assignment status'), ('create_shift_assignment', 'Create shift assignment'), ('remove_shift_assignment', 'Remove shift assignment'), ('update_event_status', 'Update event status')], max_length=50)),
                ('label', models.CharField(help_text='Button label shown to users', max_length=100)),
                ('description', models.TextField(blank=True)),
                ('config', models.JSONField(blank=True, default=dict, help_text='Action configuration and defaults')),
                ('updates_ticket_status', models.CharField(blank=True, choices=[('open', 'Open'), ('todo', 'To Do'), ('inprogress', 'In Progress'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('canceled', 'Canceled')], max_length=20)),
                ('run_when', models.CharField(choices=[('manual', 'Manual'), ('on_create', 'On ticket creation'), ('on_claim', 'On ticket claim'), ('on_unclaim', 'On ticket unclaim'), ('on_update', 'On ticket update')], default='manual', help_text='When this action should be executed. Manual actions appear as buttons. Automatic actions run without user interaction.', max_length=20)),
                ('button_color', models.CharField(choices=[('primary', 'Primary (blue)'), ('danger', 'Danger (red)'), ('secondary', 'Secondary (gray)'), ('success', 'Success (green)'), ('warning', 'Warning (yellow)'), ('link', 'link (no-color)')], default='secondary', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, help_text='Rendered markdown description for this ticket')),
                ('status', models.CharField(choices=[('open', 'Open'), ('todo', 'To Do'), ('inprogress', 'In Progress'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='open', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(default=3)),
                ('claimable', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_assigned', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='events.event')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='orgs.organization')),
                ('person', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='people.person')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets_reported', to=settings.AUTH_USER_MODEL)),
                ('shift', models.ForeignKey(blank=True, help_text='Shift this ticket applies to; defaults to event default shift', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='events.shift')),
            ],
        ),
        migrations.CreateModel(
            name='TicketAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Ticket created'), ('updated', 'Ticket updated'), ('claimed', 'Ticket claimed'), ('unclaimed', 'Ticket unclaimed'), ('status_changed', 'Status changed'), ('action_run', 'Action executed'), ('action_failed', 'Action failed'), ('system', 'System event')], max_length=50)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional structured context')),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Null means system', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TicketBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('reason', models.TextField(blank=True)),
                ('claimable', models.BooleanField(default=True)),
                ('default_priority', models.PositiveSmallIntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_batches_created', to=settings.AUTH_USER_MODEL)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_batches', to='events.event')),
                ('org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ticket_batches', to='orgs.organization')),
                ('shift', models.ForeignKey(blank=True, help_text='Shift this ticket applies to; defaults to event default shift', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_batches', related_query_name='ticket_batch', to='events.shift')),
            ],
        ),
        migrations.AddField(
            model_name='ticket',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.ticketbatch'),
        ),
        migrations.CreateModel(
            name='TicketTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description_template', models.TextField(default='', help_text='Markdown template rendered into the ticket description')),
                ('ticket_name_template', models.CharField(max_length=200)),
                ('default_priority', models.PositiveSmallIntegerField(default=3)),
                ('is_active', models.BooleanField(default=True)),
                ('claimable', models.BooleanField(default=True)),
                ('max_tickets', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('action_templates', models.ManyToManyField(blank=True, related_name='ticket_templates', to='tickets.ticketactiontemplate')),
                ('org', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ticket_templates', to='orgs.organization')),
            ],
        ),
        migrations.CreateModel(
            name='TicketAction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('run_when', models.CharField(choices=[('manual', 'Manual'), ('on_create', 'On ticket creation'), ('on_claim', 'On ticket claim'), ('on_unclaim', 'On ticket unclaim'), ('on_update', 'On ticket update')], default='manual', max_length=20)),
                ('action_type', models.CharField(choices=[('noop', 'No-op (status changes only)'), ('update_shift_status', 'Update shift assignment status'), ('create_shift_assignment', 'Create shift assignment'), ('remove_shift_assignment', 'Remove shift assignment'), ('update_event_status', 'Update event status')], max_length=50)),
                ('button_color', models.CharField(choices=[('primary', 'Primary (blue)'), ('danger', 'Danger (red)'), ('secondary', 'Secondary (gray)'), ('success', 'Success (green)'), ('warning', 'Warning (yellow)'), ('link', 'link (no-color)')], default='secondary', max_length=20)),
                ('updates_ticket_status', models.CharField(blank=True, choices=[('open', 'Open'), ('todo', 'To Do'), ('inprogress', 'In Progress'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('canceled', 'Canceled')], max_length=20)),
                ('label', models.CharField(max_length=100)),
                ('config', models.JSONField(default=dict)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actions', to='tickets.ticket')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_actions', to='tickets.ticketactiontemplate')),
            ],
            options={
                'indexes': [models.Index(fields=['ticket', 'run_when', 'is_completed'], name='tic_runwhen_completed_idx')],
            },
        ),
    ]
