# Generated by Django 5.2.9 on 2025-12-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketaction',
            name='action_type',
            field=models.CharField(choices=[('noop', 'No-op (ticket status changes only)'), ('update_shift_status', 'Update shift assignment status'), ('upsert_shift_assignment', 'Upsert shift assignment'), ('remove_shift_assignment', 'Remove shift assignment'), ('update_event_status', 'Update event status')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketactiontemplate',
            name='action_type',
            field=models.CharField(choices=[('noop', 'No-op (ticket status changes only)'), ('update_shift_status', 'Update shift assignment status'), ('upsert_shift_assignment', 'Upsert shift assignment'), ('remove_shift_assignment', 'Remove shift assignment'), ('update_event_status', 'Update event status')], max_length=50),
        ),
    ]
