# Generated by Django 5.2.9 on 2025-12-27 22:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_initial'),
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='Shift this ticket applies to; defaults to event default shift', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='events.shift'),
        ),
        migrations.AddField(
            model_name='ticketbatch',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='Shift this ticket applies to; defaults to event default shift', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_batches', related_query_name='ticket_batch', to='events.shift'),
        ),
    ]
