# Generated by Django 5.2.9 on 2025-12-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='tickettemplate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tickettemplate',
            name='instructions',
        ),
        migrations.RemoveField(
            model_name='tickettemplate',
            name='message_template',
        ),
        migrations.AddField(
            model_name='tickettemplate',
            name='description_template',
            field=models.TextField(default='', help_text='Markdown template rendered into the ticket description'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='description',
            field=models.TextField(blank=True, help_text='Rendered markdown description for this ticket'),
        ),
    ]
