# Generated by Django 5.2.9 on 2025-12-27 23:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_shift_ticketbatch_shift'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketaction',
            name='updates_ticket_status',
            field=models.CharField(blank=True, choices=[('open', 'Open'), ('todo', 'To Do'), ('inprogress', 'In Progress'), ('blocked', 'Blocked'), ('completed', 'Completed'), ('canceled', 'Canceled')], default='', max_length=20),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TicketAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('created', 'Ticket created'), ('updated', 'Ticket updated'), ('claimed', 'Ticket claimed'), ('unclaimed', 'Ticket unclaimed'), ('status_changed', 'Status changed'), ('action_run', 'Action executed'), ('action_failed', 'Action failed'), ('system', 'System event')], max_length=50)),
                ('message', models.TextField()),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Optional structured context')),
                ('success', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='Null means system', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_audit_logs', to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
