# Generated by Django 5.2.9 on 2025-12-28 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orgs', '0001_initial'),
        ('tickets', '0002_alter_ticketaction_action_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tickettemplate',
            unique_together={('org', 'name')},
        ),
    ]
