# Generated by Django 5.2.9 on 2025-12-28 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_ticketaction_updates_ticket_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketactiontemplate',
            name='slug',
            field=models.SlugField(default='', help_text='Slug to uniquely identify this action template', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ticketaction',
            name='action_type',
            field=models.CharField(choices=[('noop', 'No-op (status changes only)'), ('update_shift_status', 'Update shift assignment status'), ('create_shift_assignment', 'Create shift assignment'), ('remove_shift_assignment', 'Remove shift assignment'), ('update_event_status', 'Update event status')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketactiontemplate',
            name='action_type',
            field=models.CharField(choices=[('noop', 'No-op (status changes only)'), ('update_shift_status', 'Update shift assignment status'), ('create_shift_assignment', 'Create shift assignment'), ('remove_shift_assignment', 'Remove shift assignment'), ('update_event_status', 'Update event status')], max_length=50),
        ),
    ]
