# Generated by Django 5.2.9 on 2025-12-29 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_alter_tickettemplate_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(0, 'P0 - Emergency (Do Now)'), (1, 'P1 - Very High'), (2, 'P2 - High'), (3, 'P3 - Normal'), (4, 'P4 - Low'), (5, 'P5 - Very Low')], default=3),
        ),
        migrations.AlterField(
            model_name='ticketaction',
            name='action_type',
            field=models.CharField(choices=[('noop', 'No-op (ticket status changes only)'), ('update_shift_status', 'Update shift assignment status'), ('upsert_shift_assignment', 'Upsert shift assignment'), ('update_event_status', 'Update event status'), ('upsert_tag', 'Upsert tag on person')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketactiontemplate',
            name='action_type',
            field=models.CharField(choices=[('noop', 'No-op (ticket status changes only)'), ('update_shift_status', 'Update shift assignment status'), ('upsert_shift_assignment', 'Upsert shift assignment'), ('update_event_status', 'Update event status'), ('upsert_tag', 'Upsert tag on person')], max_length=50),
        ),
    ]
