# Generated by Django 5.2.9 on 2025-12-29 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_priority_alter_ticketaction_action_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketaction',
            name='action_type',
            field=models.CharField(choices=[('noop', 'No-op (ticket status changes only)'), ('update_shift_status', 'Update shift assignment status'), ('upsert_shift_assignment', 'Upsert shift assignment'), ('update_event_status', 'Update event status'), ('upsert_tag', 'Upsert tag on person'), ('remove_tag', 'Remove tag from person')], max_length=50),
        ),
        migrations.AlterField(
            model_name='ticketactiontemplate',
            name='action_type',
            field=models.CharField(choices=[('noop', 'No-op (ticket status changes only)'), ('update_shift_status', 'Update shift assignment status'), ('upsert_shift_assignment', 'Upsert shift assignment'), ('update_event_status', 'Update event status'), ('upsert_tag', 'Upsert tag on person'), ('remove_tag', 'Remove tag from person')], max_length=50),
        ),
    ]
