# Generated by Django 5.2.9 on 2025-12-29 18:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticketaction_action_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template ticket was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='tickets.tickettemplate'),
        ),
        migrations.AddField(
            model_name='ticketbatch',
            name='template',
            field=models.ForeignKey(blank=True, help_text='Template this batch was created from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ticket_batches', to='tickets.tickettemplate'),
        ),
    ]
